import './screens/register.js'
import './screens/login.js'
import './screens/story.js'
import './components/header.js'
import './components/createPost.js'
import './components/inputWrapper.js'
import './components/postItem.js'
import './components/listPost.js'
import './navigo.js'

